### ISSUE TITLE
Help with documentation and code comments

### ISSUE THREAD

**Issue by Kashyapdevesh** [Kashyapdevesh/Manga-Newsletter#1]
The entire code was written over a very short period of time, and I didn't pay much attention to code commenting styles and documentation paradigms. 

Now that the scope of the project is increasing, I'm having issues with keeping logs and track of the project.

I need help with ordering the comments in the code files and further, if you have any ideas or suggestions, please do share

**Comment by srigundeti10** [comment]
if the code is in c then i would like to do this please

**Comment by ibrahim-ogunbiyi** [comment]
If the code is in python please assign the task to me. Thnanks

**Comment by Kashyapdevesh** [comment]
> if the code is in c then i would like to do this please

Hi, sorry the code is completely in python as of now.

**Comment by Kashyapdevesh** [comment]
> If the code is in python please assign the task to me. Thnanks

Sure, no problem, do let me know if you need any clarification or any sort of help.
