### ISSUE TITLE
Implement Python classes and objects

### ISSUE THREAD

**Issue by Kashyapdevesh** [Kashyapdevesh/Manga-Newsletter#6]
The python codes in the project are written while following the functional programming paradigm. The functions written can easily be converted into python class object format and be made modular.

The given issue is good to get a rough estimate of the project and is a beginner-friendly issue as the codebase is still growing and this issue can easily be resolved at this stage.

**Comment by sujal-goswami** [comment]
hey Lashyapdevesh I want to work on this can you assign this to me.

**Comment by ShivamGarg2910** [comment]
@Kashyapdevesh, please assign to me

**Comment by Kashyapdevesh** [comment]
Hi, thx. for your interest, this is an open-ended issue meant to familiarize you with the codebase, so I can't personally assign it.

However, you can push the Pull Request after modifying some parts of the project if not the whole.
